// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/GetLearnRatingScoreReportForStudentInVisitingLog/GetLearnRatingScoreReportForStudentInVisitingLog.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_FullMethodName = "/GetLearnRatingScoreReportForStudentInVisitingLog/GetLearnRatingScoreReportForStudentInVisitingLog"
)

// GetLearnRatingScoreReportForStudentInVisitingLogClient is the client API for GetLearnRatingScoreReportForStudentInVisitingLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetLearnRatingScoreReportForStudentInVisitingLogClient interface {
	GetLearnRatingScoreReportForStudentInVisitingLog(ctx context.Context, in *GetScoreAndVisitngRequest, opts ...grpc.CallOption) (*GetScoreAndVisitngResponse, error)
}

type getLearnRatingScoreReportForStudentInVisitingLogClient struct {
	cc grpc.ClientConnInterface
}

func NewGetLearnRatingScoreReportForStudentInVisitingLogClient(cc grpc.ClientConnInterface) GetLearnRatingScoreReportForStudentInVisitingLogClient {
	return &getLearnRatingScoreReportForStudentInVisitingLogClient{cc}
}

func (c *getLearnRatingScoreReportForStudentInVisitingLogClient) GetLearnRatingScoreReportForStudentInVisitingLog(ctx context.Context, in *GetScoreAndVisitngRequest, opts ...grpc.CallOption) (*GetScoreAndVisitngResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScoreAndVisitngResponse)
	err := c.cc.Invoke(ctx, GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetLearnRatingScoreReportForStudentInVisitingLogServer is the server API for GetLearnRatingScoreReportForStudentInVisitingLog service.
// All implementations must embed UnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer
// for forward compatibility.
type GetLearnRatingScoreReportForStudentInVisitingLogServer interface {
	GetLearnRatingScoreReportForStudentInVisitingLog(context.Context, *GetScoreAndVisitngRequest) (*GetScoreAndVisitngResponse, error)
	mustEmbedUnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer()
}

// UnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer struct{}

func (UnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer) GetLearnRatingScoreReportForStudentInVisitingLog(context.Context, *GetScoreAndVisitngRequest) (*GetScoreAndVisitngResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLearnRatingScoreReportForStudentInVisitingLog not implemented")
}
func (UnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer) mustEmbedUnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer() {
}
func (UnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer) testEmbeddedByValue() {}

// UnsafeGetLearnRatingScoreReportForStudentInVisitingLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetLearnRatingScoreReportForStudentInVisitingLogServer will
// result in compilation errors.
type UnsafeGetLearnRatingScoreReportForStudentInVisitingLogServer interface {
	mustEmbedUnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer()
}

func RegisterGetLearnRatingScoreReportForStudentInVisitingLogServer(s grpc.ServiceRegistrar, srv GetLearnRatingScoreReportForStudentInVisitingLogServer) {
	// If the following call pancis, it indicates UnimplementedGetLearnRatingScoreReportForStudentInVisitingLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetLearnRatingScoreReportForStudentInVisitingLog_ServiceDesc, srv)
}

func _GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreAndVisitngRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetLearnRatingScoreReportForStudentInVisitingLogServer).GetLearnRatingScoreReportForStudentInVisitingLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetLearnRatingScoreReportForStudentInVisitingLogServer).GetLearnRatingScoreReportForStudentInVisitingLog(ctx, req.(*GetScoreAndVisitngRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetLearnRatingScoreReportForStudentInVisitingLog_ServiceDesc is the grpc.ServiceDesc for GetLearnRatingScoreReportForStudentInVisitingLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetLearnRatingScoreReportForStudentInVisitingLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetLearnRatingScoreReportForStudentInVisitingLog",
	HandlerType: (*GetLearnRatingScoreReportForStudentInVisitingLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLearnRatingScoreReportForStudentInVisitingLog",
			Handler:    _GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetLearnRatingScoreReportForStudentInVisitingLog/GetLearnRatingScoreReportForStudentInVisitingLog.proto",
}
