// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/GetLearnRatingScoreReportForStudentInVisitingLog/GetLearnRatingScoreReportForStudentInVisitingLog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScoreAndVisitngRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` //eee7152e-a195-4696-b37b-cc83da0afe59
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreAndVisitngRequest) Reset() {
	*x = GetScoreAndVisitngRequest{}
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreAndVisitngRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreAndVisitngRequest) ProtoMessage() {}

func (x *GetScoreAndVisitngRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreAndVisitngRequest.ProtoReflect.Descriptor instead.
func (*GetScoreAndVisitngRequest) Descriptor() ([]byte, []int) {
	return file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescGZIP(), []int{0}
}

func (x *GetScoreAndVisitngRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScoreAndVisitngResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreAndVisitngResponse) Reset() {
	*x = GetScoreAndVisitngResponse{}
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreAndVisitngResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreAndVisitngResponse) ProtoMessage() {}

func (x *GetScoreAndVisitngResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreAndVisitngResponse.ProtoReflect.Descriptor instead.
func (*GetScoreAndVisitngResponse) Descriptor() ([]byte, []int) {
	return file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescGZIP(), []int{1}
}

var File_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto protoreflect.FileDescriptor

const file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc = "" +
	"\n" +
	"mproto/GetLearnRatingScoreReportForStudentInVisitingLog/GetLearnRatingScoreReportForStudentInVisitingLog.proto\"+\n" +
	"\x19GetScoreAndVisitngRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\x1aGetScoreAndVisitngResponse2\x9f\x01\n" +
	"0GetLearnRatingScoreReportForStudentInVisitingLog\x12k\n" +
	"0GetLearnRatingScoreReportForStudentInVisitingLog\x12\x1a.GetScoreAndVisitngRequest\x1a\x1b.GetScoreAndVisitngResponseBQZOmireaattendanceapp/proto/GetLearnRatingScoreReportForStudentInVisitingLog;protob\x06proto3"

var (
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescOnce sync.Once
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescData []byte
)

func file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescGZIP() []byte {
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescOnce.Do(func() {
		file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc), len(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc)))
	})
	return file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescData
}

var file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_goTypes = []any{
	(*GetScoreAndVisitngRequest)(nil),  // 0: GetScoreAndVisitngRequest
	(*GetScoreAndVisitngResponse)(nil), // 1: GetScoreAndVisitngResponse
}
var file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_depIdxs = []int32{
	0, // 0: GetLearnRatingScoreReportForStudentInVisitingLog.GetLearnRatingScoreReportForStudentInVisitingLog:input_type -> GetScoreAndVisitngRequest
	1, // 1: GetLearnRatingScoreReportForStudentInVisitingLog.GetLearnRatingScoreReportForStudentInVisitingLog:output_type -> GetScoreAndVisitngResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_init()
}
func file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_init() {
	if File_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc), len(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_goTypes,
		DependencyIndexes: file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_depIdxs,
		MessageInfos:      file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes,
	}.Build()
	File_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto = out.File
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_goTypes = nil
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_depIdxs = nil
}
