// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/GetLearnRatingScoreReportForStudentInVisitingLog/GetLearnRatingScoreReportForStudentInVisitingLog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScoreAndVisitngRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` //eee7152e-a195-4696-b37b-cc83da0afe59
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreAndVisitngRequest) Reset() {
	*x = GetScoreAndVisitngRequest{}
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreAndVisitngRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreAndVisitngRequest) ProtoMessage() {}

func (x *GetScoreAndVisitngRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreAndVisitngRequest.ProtoReflect.Descriptor instead.
func (*GetScoreAndVisitngRequest) Descriptor() ([]byte, []int) {
	return file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescGZIP(), []int{0}
}

func (x *GetScoreAndVisitngRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScoreAndVisitngResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CurrentControl  float64                `protobuf:"fixed64,2,opt,name=current_control,json=currentControl,proto3" json:"current_control,omitempty"`    // Текущий контроль (Макс. 40)
	Attendance      float64                `protobuf:"fixed64,3,opt,name=attendance,proto3" json:"attendance,omitempty"`                                  // Посещения (Макс. 30)
	Achievements    float64                `protobuf:"fixed64,4,opt,name=achievements,proto3" json:"achievements,omitempty"`                              // Достижения (Макс. 10)
	SemesterControl float64                `protobuf:"fixed64,5,opt,name=semester_control,json=semesterControl,proto3" json:"semester_control,omitempty"` // Семестровый контроль (Макс. 30)
	Total           float64                `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetScoreAndVisitngResponse) Reset() {
	*x = GetScoreAndVisitngResponse{}
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreAndVisitngResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreAndVisitngResponse) ProtoMessage() {}

func (x *GetScoreAndVisitngResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreAndVisitngResponse.ProtoReflect.Descriptor instead.
func (*GetScoreAndVisitngResponse) Descriptor() ([]byte, []int) {
	return file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescGZIP(), []int{1}
}

func (x *GetScoreAndVisitngResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetScoreAndVisitngResponse) GetCurrentControl() float64 {
	if x != nil {
		return x.CurrentControl
	}
	return 0
}

func (x *GetScoreAndVisitngResponse) GetAttendance() float64 {
	if x != nil {
		return x.Attendance
	}
	return 0
}

func (x *GetScoreAndVisitngResponse) GetAchievements() float64 {
	if x != nil {
		return x.Achievements
	}
	return 0
}

func (x *GetScoreAndVisitngResponse) GetSemesterControl() float64 {
	if x != nil {
		return x.SemesterControl
	}
	return 0
}

func (x *GetScoreAndVisitngResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetScoreAndVisitngResponseList struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ResponseList  []*GetScoreAndVisitngResponse `protobuf:"bytes,1,rep,name=responseList,proto3" json:"responseList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreAndVisitngResponseList) Reset() {
	*x = GetScoreAndVisitngResponseList{}
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreAndVisitngResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreAndVisitngResponseList) ProtoMessage() {}

func (x *GetScoreAndVisitngResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreAndVisitngResponseList.ProtoReflect.Descriptor instead.
func (*GetScoreAndVisitngResponseList) Descriptor() ([]byte, []int) {
	return file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescGZIP(), []int{2}
}

func (x *GetScoreAndVisitngResponseList) GetResponseList() []*GetScoreAndVisitngResponse {
	if x != nil {
		return x.ResponseList
	}
	return nil
}

var File_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto protoreflect.FileDescriptor

const file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc = "" +
	"\n" +
	"mproto/GetLearnRatingScoreReportForStudentInVisitingLog/GetLearnRatingScoreReportForStudentInVisitingLog.proto\"+\n" +
	"\x19GetScoreAndVisitngRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xde\x01\n" +
	"\x1aGetScoreAndVisitngResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fcurrent_control\x18\x02 \x01(\x01R\x0ecurrentControl\x12\x1e\n" +
	"\n" +
	"attendance\x18\x03 \x01(\x01R\n" +
	"attendance\x12\"\n" +
	"\fachievements\x18\x04 \x01(\x01R\fachievements\x12)\n" +
	"\x10semester_control\x18\x05 \x01(\x01R\x0fsemesterControl\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x01R\x05total\"a\n" +
	"\x1eGetScoreAndVisitngResponseList\x12?\n" +
	"\fresponseList\x18\x01 \x03(\v2\x1b.GetScoreAndVisitngResponseR\fresponseList2\x9f\x01\n" +
	"0GetLearnRatingScoreReportForStudentInVisitingLog\x12k\n" +
	"0GetLearnRatingScoreReportForStudentInVisitingLog\x12\x1a.GetScoreAndVisitngRequest\x1a\x1b.GetScoreAndVisitngResponseBQZOmireaattendanceapp/proto/GetLearnRatingScoreReportForStudentInVisitingLog;protob\x06proto3"

var (
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescOnce sync.Once
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescData []byte
)

func file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescGZIP() []byte {
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescOnce.Do(func() {
		file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc), len(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc)))
	})
	return file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDescData
}

var file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_goTypes = []any{
	(*GetScoreAndVisitngRequest)(nil),      // 0: GetScoreAndVisitngRequest
	(*GetScoreAndVisitngResponse)(nil),     // 1: GetScoreAndVisitngResponse
	(*GetScoreAndVisitngResponseList)(nil), // 2: GetScoreAndVisitngResponseList
}
var file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_depIdxs = []int32{
	1, // 0: GetScoreAndVisitngResponseList.responseList:type_name -> GetScoreAndVisitngResponse
	0, // 1: GetLearnRatingScoreReportForStudentInVisitingLog.GetLearnRatingScoreReportForStudentInVisitingLog:input_type -> GetScoreAndVisitngRequest
	1, // 2: GetLearnRatingScoreReportForStudentInVisitingLog.GetLearnRatingScoreReportForStudentInVisitingLog:output_type -> GetScoreAndVisitngResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_init()
}
func file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_init() {
	if File_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc), len(file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_goTypes,
		DependencyIndexes: file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_depIdxs,
		MessageInfos:      file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_msgTypes,
	}.Build()
	File_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto = out.File
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_goTypes = nil
	file_proto_GetLearnRatingScoreReportForStudentInVisitingLog_GetLearnRatingScoreReportForStudentInVisitingLog_proto_depIdxs = nil
}
