// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/GetMeInfo/GetMeInfo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TakeUserData_GetMeInfo_FullMethodName = "/TakeUserData/GetMeInfo"
)

// TakeUserDataClient is the client API for TakeUserData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TakeUserDataClient interface {
	GetMeInfo(ctx context.Context, in *GetMeInfoRequest, opts ...grpc.CallOption) (*GetMeInfoResponse, error)
}

type takeUserDataClient struct {
	cc grpc.ClientConnInterface
}

func NewTakeUserDataClient(cc grpc.ClientConnInterface) TakeUserDataClient {
	return &takeUserDataClient{cc}
}

func (c *takeUserDataClient) GetMeInfo(ctx context.Context, in *GetMeInfoRequest, opts ...grpc.CallOption) (*GetMeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeInfoResponse)
	err := c.cc.Invoke(ctx, TakeUserData_GetMeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TakeUserDataServer is the server API for TakeUserData service.
// All implementations must embed UnimplementedTakeUserDataServer
// for forward compatibility.
type TakeUserDataServer interface {
	GetMeInfo(context.Context, *GetMeInfoRequest) (*GetMeInfoResponse, error)
	mustEmbedUnimplementedTakeUserDataServer()
}

// UnimplementedTakeUserDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTakeUserDataServer struct{}

func (UnimplementedTakeUserDataServer) GetMeInfo(context.Context, *GetMeInfoRequest) (*GetMeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeInfo not implemented")
}
func (UnimplementedTakeUserDataServer) mustEmbedUnimplementedTakeUserDataServer() {}
func (UnimplementedTakeUserDataServer) testEmbeddedByValue()                      {}

// UnsafeTakeUserDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TakeUserDataServer will
// result in compilation errors.
type UnsafeTakeUserDataServer interface {
	mustEmbedUnimplementedTakeUserDataServer()
}

func RegisterTakeUserDataServer(s grpc.ServiceRegistrar, srv TakeUserDataServer) {
	// If the following call pancis, it indicates UnimplementedTakeUserDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TakeUserData_ServiceDesc, srv)
}

func _TakeUserData_GetMeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TakeUserDataServer).GetMeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TakeUserData_GetMeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TakeUserDataServer).GetMeInfo(ctx, req.(*GetMeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TakeUserData_ServiceDesc is the grpc.ServiceDesc for TakeUserData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TakeUserData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TakeUserData",
	HandlerType: (*TakeUserDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeInfo",
			Handler:    _TakeUserData_GetMeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetMeInfo/GetMeInfo.proto",
}
