// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/GetAvailableVisitingLogsOfStudent/GetAvailableVisitingLogsOfStudent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableVisitingLogsOfStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentRequest) Reset() {
	*x = GetAvailableVisitingLogsOfStudentRequest{}
	mi := &file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentRequest) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescGZIP(), []int{0}
}

type GetAvailableVisitingLogsOfStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InternalId    string                 `protobuf:"bytes,3,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	Flagged       bool                   `protobuf:"varint,4,opt,name=flagged,proto3" json:"flagged,omitempty"`
	EncodedMeta   string                 `protobuf:"bytes,5,opt,name=encoded_meta,json=encodedMeta,proto3" json:"encoded_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse{}
	mi := &file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse) Descriptor() ([]byte, []int) {
	return file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvailableVisitingLogsOfStudentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

func (x *GetAvailableVisitingLogsOfStudentResponse) GetEncodedMeta() string {
	if x != nil {
		return x.EncodedMeta
	}
	return ""
}

type GetAvailableVisitingLogsOfStudentResponseList struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Items         []*GetAvailableVisitingLogsOfStudentResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponseList) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponseList{}
	mi := &file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponseList) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponseList.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponseList) Descriptor() ([]byte, []int) {
	return file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAvailableVisitingLogsOfStudentResponseList) GetItems() []*GetAvailableVisitingLogsOfStudentResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto protoreflect.FileDescriptor

const file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDesc = "" +
	"\n" +
	"Oproto/GetAvailableVisitingLogsOfStudent/GetAvailableVisitingLogsOfStudent.proto\"*\n" +
	"(GetAvailableVisitingLogsOfStudentRequest\"\xad\x01\n" +
	")GetAvailableVisitingLogsOfStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vinternal_id\x18\x03 \x01(\tR\n" +
	"internalId\x12\x18\n" +
	"\aflagged\x18\x04 \x01(\bR\aflagged\x12!\n" +
	"\fencoded_meta\x18\x05 \x01(\tR\vencodedMeta\"q\n" +
	"-GetAvailableVisitingLogsOfStudentResponseList\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.GetAvailableVisitingLogsOfStudentResponseR\x05items2\x8c\x01\n" +
	"\x0eTakeUUIDandETC\x12z\n" +
	"!GetAvailableVisitingLogsOfStudent\x12).GetAvailableVisitingLogsOfStudentRequest\x1a*.GetAvailableVisitingLogsOfStudentResponseBBZ@mireaattendanceapp/proto/GetAvailableVisitingLogsOfStudent;protob\x06proto3"

var (
	file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescOnce sync.Once
	file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescData []byte
)

func file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescGZIP() []byte {
	file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescOnce.Do(func() {
		file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDesc), len(file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDesc)))
	})
	return file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDescData
}

var file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_goTypes = []any{
	(*GetAvailableVisitingLogsOfStudentRequest)(nil),      // 0: GetAvailableVisitingLogsOfStudentRequest
	(*GetAvailableVisitingLogsOfStudentResponse)(nil),     // 1: GetAvailableVisitingLogsOfStudentResponse
	(*GetAvailableVisitingLogsOfStudentResponseList)(nil), // 2: GetAvailableVisitingLogsOfStudentResponseList
}
var file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_depIdxs = []int32{
	1, // 0: GetAvailableVisitingLogsOfStudentResponseList.items:type_name -> GetAvailableVisitingLogsOfStudentResponse
	0, // 1: TakeUUIDandETC.GetAvailableVisitingLogsOfStudent:input_type -> GetAvailableVisitingLogsOfStudentRequest
	1, // 2: TakeUUIDandETC.GetAvailableVisitingLogsOfStudent:output_type -> GetAvailableVisitingLogsOfStudentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_init()
}
func file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_init() {
	if File_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDesc), len(file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_goTypes,
		DependencyIndexes: file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_depIdxs,
		MessageInfos:      file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_msgTypes,
	}.Build()
	File_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto = out.File
	file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_goTypes = nil
	file_proto_GetAvailableVisitingLogsOfStudent_GetAvailableVisitingLogsOfStudent_proto_depIdxs = nil
}
