// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/GetAvailableVisitingLogsOfStudent/GetAvailableVisitingLogsOfStudent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TakeUUIDandETC_GetAvailableVisitingLogsOfStudent_FullMethodName = "/TakeUUIDandETC/GetAvailableVisitingLogsOfStudent"
)

// TakeUUIDandETCClient is the client API for TakeUUIDandETC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TakeUUIDandETCClient interface {
	GetAvailableVisitingLogsOfStudent(ctx context.Context, in *GetAvailableVisitingLogsOfStudentRequest, opts ...grpc.CallOption) (*GetAvailableVisitingLogsOfStudentResponse, error)
}

type takeUUIDandETCClient struct {
	cc grpc.ClientConnInterface
}

func NewTakeUUIDandETCClient(cc grpc.ClientConnInterface) TakeUUIDandETCClient {
	return &takeUUIDandETCClient{cc}
}

func (c *takeUUIDandETCClient) GetAvailableVisitingLogsOfStudent(ctx context.Context, in *GetAvailableVisitingLogsOfStudentRequest, opts ...grpc.CallOption) (*GetAvailableVisitingLogsOfStudentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableVisitingLogsOfStudentResponse)
	err := c.cc.Invoke(ctx, TakeUUIDandETC_GetAvailableVisitingLogsOfStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TakeUUIDandETCServer is the server API for TakeUUIDandETC service.
// All implementations must embed UnimplementedTakeUUIDandETCServer
// for forward compatibility.
type TakeUUIDandETCServer interface {
	GetAvailableVisitingLogsOfStudent(context.Context, *GetAvailableVisitingLogsOfStudentRequest) (*GetAvailableVisitingLogsOfStudentResponse, error)
	mustEmbedUnimplementedTakeUUIDandETCServer()
}

// UnimplementedTakeUUIDandETCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTakeUUIDandETCServer struct{}

func (UnimplementedTakeUUIDandETCServer) GetAvailableVisitingLogsOfStudent(context.Context, *GetAvailableVisitingLogsOfStudentRequest) (*GetAvailableVisitingLogsOfStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableVisitingLogsOfStudent not implemented")
}
func (UnimplementedTakeUUIDandETCServer) mustEmbedUnimplementedTakeUUIDandETCServer() {}
func (UnimplementedTakeUUIDandETCServer) testEmbeddedByValue()                        {}

// UnsafeTakeUUIDandETCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TakeUUIDandETCServer will
// result in compilation errors.
type UnsafeTakeUUIDandETCServer interface {
	mustEmbedUnimplementedTakeUUIDandETCServer()
}

func RegisterTakeUUIDandETCServer(s grpc.ServiceRegistrar, srv TakeUUIDandETCServer) {
	// If the following call pancis, it indicates UnimplementedTakeUUIDandETCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TakeUUIDandETC_ServiceDesc, srv)
}

func _TakeUUIDandETC_GetAvailableVisitingLogsOfStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableVisitingLogsOfStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TakeUUIDandETCServer).GetAvailableVisitingLogsOfStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TakeUUIDandETC_GetAvailableVisitingLogsOfStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TakeUUIDandETCServer).GetAvailableVisitingLogsOfStudent(ctx, req.(*GetAvailableVisitingLogsOfStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TakeUUIDandETC_ServiceDesc is the grpc.ServiceDesc for TakeUUIDandETC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TakeUUIDandETC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TakeUUIDandETC",
	HandlerType: (*TakeUUIDandETCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableVisitingLogsOfStudent",
			Handler:    _TakeUUIDandETC_GetAvailableVisitingLogsOfStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetAvailableVisitingLogsOfStudent/GetAvailableVisitingLogsOfStudent.proto",
}
